name: production
on:
  push:
    branches: [main]
    paths-ignore:
      - '**/package.json'
      - 'packages/sdk/example/**'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: install dependencies
        run: yarn

      - name: build
        run: yarn build

      - name: npm setup
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: release
        run: yarn release --ci --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: merge main to stg
        run: |
          git checkout stg
          git merge main
          git push origin stg
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
