name: sdk-release
on:
  push:
    branches: [main, stg]
    paths:
      - 'packages/sdk/**'
      - '**/package.json'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: install dependencies
        run: yarn

      - name: build
        run: yarn build

      - name: npm setup
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: release
        run: |
          if [ "${GITHUB_REF}" = "refs/heads/stg" ]; then
            yarn release --ci --verbose --preRelease=nightly
          else
            yarn release --ci --verbose
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: merge main to stg
        if: github.ref == 'refs/heads/main'
        run: |
          git checkout stg
          git merge main
          git push origin stg
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: example deploy
        if: github.ref == 'refs/heads/stg'
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
